#-------------------------------
# General Site Settings

title: yoichow
logo: 
author: Jiyuan Zhou
description: 
email: 
phone: (415) 509-1577
address: 515 Sycamore Lane, Room 309, Davis, CA, 95616
copyright: Copyright &copy; 2020 Designed by [Themefisher](https://themefisher.com) & Developed by [Getjekyllthemes](https://getjekyllthemes.com)

menu:
- {name: About, link: '/about'}
# - {name: Blog, link: '/blog'}
# - {name: Portfolio, link: '/portfolio'}
- {name: Contact, link: '/contact'}

#-------------------------------
# Google Analytics Section

# Analytics helps you understand who visits your website.
# Learn more at: http://support.google.com/analytics/answer/1008065

# NOTE: If you want to use Google Analytics for basic web tracking: Just uncomment and enter your UA-Code here.

google-analytics: # UA-XXXXXX-X


#-------------------------------
# Comment Section (Disqus)

disqus-identifier: # Add your shortname for Disqus Comment. For example mr-brown


#-------------------------------
# Hero Section

hero:
  hero-title: Hi! I’m <br> Jiyuan Zhou <br> Pre-Med Student

social:
- {icon: "ti-facebook", link: "#"}
- {icon: "ti-instagram", link: "#"}
- {icon: "ti-dribbble", link: "#"}
- {icon: "ti-twitter", link: "#"}


#-------------------------------
# About (Section and Page)

# About Section
blurb:
  I'm a pre-med student who current studies Pharmaceutical Chemistry in UC Davis. 
  As a diligent Senior college student, I maintained a full GPA of 4.0 for all four years in UC Davis and received scholarship for my hardworks.
  I'm interested in Chemistry, Biology, and Neuro-Science.

blurb-btn-link: '/about'
blurb-btn-name: know more


# About Page

# Work Process Section
work-process:
  - title : "Future Plan"
    icon : "assets/images/icons/plan.png"
    content : "I plan to go to Medical School and become a doctor. I'm specialized in Physician. My alternative Plan B is to become a research pharmacist"
    
  - title : "General Education"
    icon : "assets/images/icons/design.png"
    content : "I come from China, but I am also familar with Japanese and Japanese Culture (folklore etc). I love philosophy, politics and music as well. I know how to play piano."
    
  - title : "Medical Knowledge"
    icon : "assets/images/icons/print.png"
    content : "I had an internship in a large hospital located in the city center of Nanjing, China. I planned to strengthen my knowledge with more hospital internship."


# My Team Section
team:
  - title : "Yufeng Jin"
    image : "assets/images/team/member-1.png"
    designation : "My pal; Legue of Legend teammate"
    
  - title : "Yinhao Zhao"
    image : "assets/images/team/member-2.png"
    designation : "My pal; Legue of Legend teammate"
    
  - title : "Alex Sue"
    image : "assets/images/team/member-3.png"
    designation : "My pal; Roomate"


#-------------------------------
# Skills Section

skills-title: Skills
skills:
- {name: Medical, color: '#fdb157', value: '90%'}
- {name: Pharmaceutical Chemistry, color: '#9473e6', value: '90%'}
- {name: Biology, color: '#bdecf6', value: '70%'}
- {name: Psychology, color: '#ffbcaa', value: '50%'}


#-------------------------------
# Exprerience Section

experience-title: Experience
experience:
- {name: Medical Assistant Internship, icon: 'icon-1.png', date: 'July 2019 - Sep 2019', organization: 'Nanjing Drum Tower Hospital'}
- {name: Badass Ronin, icon: 'icon-2.png', date: 'Feb 1999 - Present', organization: 'Earth'}
- {name: Chef, icon: 'icon-3.png', date: 'Mar 2020 - Present', organization: 'University Court Apartment'}


#-------------------------------
# Education Section

education-title: Education
education:
- {name: Elementary School Student, date: '2005', organization: 'Elemetary School of Nanjing Mechanics'}
- {name: Middle School Student, date: '2011', organization: 'Nanjing Foreign Language School'}
- {name: Pharmaceutical Chemistry, date: '2017', organization: 'Univesrity of California, Daivs'}
- {name: Medical Doctor, date: 'FUTURE', organization: 'TO BE CONTINUED'}


#-------------------------------
# Services Section

services-title: Hobbies
services:
- {
    name: Art & Humanity,
    icon: ti-palette,
    description: 'Office the TV show / Music / Piano / Japanese / Japanese Culture',
    active: # Add true to select section
  }
- {
    name: Electronic Sports,
    icon: ti-vector,
    description: 'Legue of Legend / DOTA / Heroes of Storm / Diablo III / Hearthstone',
    active: true # Add true to select section
  }
- {
    name: Cooking,
    icon: ti-panel,
    description: 'Chinese Food / Japanese Food / 或者我可以下面给你吃',
    active: # Add true to select section
  }



#-------------------------------
# Portfolio (Section and Page)

# Portfolio Home Section
# portfolio-home-items:
#   - image : "assets/images/portfolio/item-1.png"
#     url: "#"
    
#   - image : "assets/images/portfolio/item-2.png"
#     url: "#"
    
#   - image : "assets/images/portfolio/item-3.png"
#     url: "#"
    
#   - image : "assets/images/portfolio/item-4.png"
#     url: "#"
    
#   - image : "assets/images/portfolio/item-5.png"
#     url: "#"


# Portfolio Page
# portfolio-label:
# - {
#     title : "UI/UX Design",
#     type : "design"
#   }
# - {
#     title : "BRANDING",
#     type : "branding"
#   }
# - {
#     title : "ILLUSTRATION",
#     type : "illustration"
#   }

# portfolio-items:
#   - image : "assets/images/portfolio/item-1.png"
#     url: "#"
#     portfolio-type:
#      - type: "design"
#      - type: "illustration"
      
#   - image : "assets/images/portfolio/item-2.png"
#     url: "#"
#     portfolio-type:
#       - type: "branding"
      
#   - image : "assets/images/portfolio/item-3.png"
#     url: "#"
#     portfolio-type:
#       - type: "illustration"
      
#   - image : "assets/images/portfolio/item-6.png"
#     url: "#"
#     portfolio-type:
#       - type: "design"
#       - type: "branding"
      
#   - image : "assets/images/portfolio/item-8.png"
#     url: "#"
#     portfolio-type:
#       - type: "illustration"
      
#   - image : "assets/images/portfolio/item-5.png"
#     url: "#"
#     portfolio-type:
#       - type: "design"
      
#   - image : "assets/images/portfolio/item-1.png"
#     url: "#"
#     portfolio-type:
#       - type: "branding"
      
#   - image : "assets/images/portfolio/item-3.png"
#     url: "#"
#     portfolio-type:
#       - type: "design"
#       - type: "illustration"
#       - type: "branding"
      
#   - image : "assets/images/portfolio/item-7.png"
#     url: "#"
#     portfolio-type:
#       - type: "illustration"


#-------------------------------
# Testimonials Section

testimonial-items:
  - name: "Wenhao Su"
    image: "assets/images/testimonial/client-0.png"
    designation : "Programmer"
    content : "周纪元老铁是真的行"
    
  - name: "Yifan Pan"
    image: "assets/images/testimonial/client-2.png"
    designation: "Electrical Engineer & Physicist"
    content: "周总牛逼啊！"
    
  - name: "Yufeng Jin"
    image: "assets/images/testimonial/client-3.png"
    designation: "Cognitive Scientist"
    content: "快点，我切他中路。"


#-------------------------------
# Client Slider Section

# client-slider-items:
#   - logo: "assets/images/clients-logo/client-logo-1.png"
#     url: "#"
    
#   - logo: "assets/images/clients-logo/client-logo-2.png"
#     url: "#"
    
#   - logo: "assets/images/clients-logo/client-logo-3.png"
#     url: "#"
    
#   - logo: "assets/images/clients-logo/client-logo-4.png"
#     url: "#"
    
#   - logo: "assets/images/clients-logo/client-logo-5.png"
#     url: "#"
    
#   - logo: "assets/images/clients-logo/client-logo-1.png"
#     url: "#"
    
#   - logo: "assets/images/clients-logo/client-logo-2.png"
#     url: "#"
    
#   - logo: "assets/images/clients-logo/client-logo-3.png"
#     url: "#"
    
#   - logo: "assets/images/clients-logo/client-logo-4.png"
#     url: "#"
    
#   - logo: "assets/images/clients-logo/client-logo-5.png"
#     url: "#"

#-------------------------------
# Contact Section

contact-title: Contact Info
contact-email: 
